# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 63078abfcf7bd0297148e02d3259faba8f82581ec0aa3ae16999fa5a55fc757a608f09626b48d41c5058e0aa02be2ce6a96c875fc07fef42ddfb42146075b863

test:
  secret_key_base: e45ff21dcd1dd5e2eaf4e6ed4ae68b3ffb452d7e03c3e2294a1d167f4a5782820501849e51616958022af5894fcf38b450d865c26dc0794c73909cf089e531b4

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
